    var buffParseObj=[
		{	"skillid":"1", "cmt":"ATK%","skillref":["atk% buff (1)","!% ATK ","buff turns (1)","! Turns"]},
		//{"skillid":"2", "cmt":"","skillref":["@"]},
		{	"skillid":"3", "cmt":"DEF%","skillref":["def% buff (3)","!% DEF ","buff turns (3)","! Turns"]},
		//{"skillid":"4", "cmt":"","skillref":["@"]},
		//{"skillid":"5", "cmt":"","skillref":["@"]},
		//{"skillid":"6", "cmt":"","skillref":["@"]},
		//{"skillid":"7", "cmt":"","skillref":["@"]},
		{	"skillid":"8", "cmt":"","skillref":["!Heal Over Turn (", "gradual heal low","!-","gradual heal high", "!) ", "buff turns (8)", "!Turns"]},
		//{"skillid":"9", "cmt":"","skillref":["@"]},
		//{"skillid":"10", "cmt":"","skillref":["@"]},
		//{"skillid":"11", "cmt":"","skillref":["@"]},
		{	"skillid":"12", "cmt":"Angel Idol","skillref":["!100% Chance to withstand a Knockout ATK (Heal ", "angel idol recover hp%", "!%) "]},
		{	"skillid":"13", "cmt":"ATK% Element","skillref":["atk% buff (13)","!% ATK of ","element buffed","! ","buff turns (13)","! Turns"]},
		{	"skillid":"14", "cmt":"DEF% Element","skillref":["def% buff (14)","!% DEF of ","element buffed","! ","buff turns (14)","! Turns"]},
		//{"skillid":"15", "cmt":"","skillref":["@"]},
		//{"skillid":"16", "cmt":"","skillref":["@"]},
		//{"skillid":"17", "cmt":"","skillref":["@"]},
		//{"skillid":"18", "cmt":"","skillref":["@"]},
		//{"skillid":"19", "cmt":"","skillref":["@"]},
		//{"skillid":"20", "cmt":"","skillref":["@"]},
		//{"skillid":"21", "cmt":"","skillref":["@"]},
		//{"skillid":"22", "cmt":"","skillref":["@"]},
		//{"skillid":"23", "cmt":"","skillref":["@"]},
		//{"skillid":"24", "cmt":"","skillref":["@"]},
		//{"skillid":"25", "cmt":"","skillref":["@"]},
		//{"skillid":"26", "cmt":"","skillref":["@"]},
		//{"skillid":"27", "cmt":"","skillref":["@"]},
		//{"skillid":"28", "cmt":"","skillref":["@"]},
		//{"skillid":"29", "cmt":"","skillref":["@"]},
		//{"skillid":"30", "cmt":"","skillref":["@"]},
		//{"skillid":"31", "cmt":"","skillref":["@"]},
		//{"skillid":"32", "cmt":"","skillref":["@"]},
		//{"skillid":"33", "cmt":"","skillref":["@"]},
		//{"skillid":"34", "cmt":"","skillref":["@"]},
		//{"skillid":"35", "cmt":"","skillref":["@"]},
		{	"skillid":"36", "cmt":"Reduce DMG","skillref":["!Reduce DMG (", "dmg reduction% buff", "!%) ", "buff turns (36)", "!Turns"]},
		{	"skillid":"37", "cmt":"BC Fill Per Turn","skillref":["increase bb gauge gradual buff","!BC Fill Per Turn ","buff turns (37)", "!Turns"]},
		//{"skillid":"38", "cmt":"","skillref":["@"]},
		//{"skillid":"39", "cmt":"","skillref":["@"]},
		{	"skillid":"40", "cmt":"Spark DMG","skillref":["spark dmg% buff", "!% Spark DMG+ ", "buff turns (40)","!Turns"]},
		//{"skillid":"41", "cmt":"","skillref":["@"]},
		//{"skillid":"42", "cmt":"","skillref":["@"]},
		//{"skillid":"43", "cmt":"","skillref":["@"]},
		//{"skillid":"44", "cmt":"","skillref":["@"]},
		//{"skillid":"45", "cmt":"","skillref":["@"]},
		//{"skillid":"46", "cmt":"","skillref":["@"]},
		/*{"skillid":"47", "cmt":"","skillref":["@"]},
		{"skillid":"48", "cmt":"","skillref":["@"]},
		{"skillid":"49", "cmt":"","skillref":["@"]},
		{"skillid":"50", "cmt":"","skillref":["@"]},*/
		{	"skillid":"51", "cmt":"Element to ATK","skillref":["!Add Fire to ATK"]},
		{	"skillid":"52", "cmt":"Element to ATK","skillref":["!Add Water to ATK"]},
		{	"skillid":"53", "cmt":"Element to ATK","skillref":["!Add Earth to ATK"]},
		{	"skillid":"54", "cmt":"Element to ATK","skillref":["!Add Thunder to ATK"]},
		{	"skillid":"55", "cmt":"Element to ATK","skillref":["!Add Light to ATK"]},
		{	"skillid":"56", "cmt":"Element to ATK","skillref":["!Add Dark to ATK"]},
		/*{"skillid":"57", "cmt":"","skillref":["@"]},
		{"skillid":"58", "cmt":"","skillref":["@"]},
		{"skillid":"59", "cmt":"","skillref":["@"]},
		{"skillid":"60", "cmt":"","skillref":["@"]},
		{"skillid":"61", "cmt":"","skillref":["@"]},
		{"skillid":"62", "cmt":"","skillref":["@"]},
		{"skillid":"63", "cmt":"","skillref":["@"]},
		{"skillid":"64", "cmt":"","skillref":["@"]},
		{"skillid":"65", "cmt":"","skillref":["@"]},
		{"skillid":"66", "cmt":"","skillref":["@"]},
		{"skillid":"67", "cmt":"","skillref":["@"]},
		{"skillid":"68", "cmt":"","skillref":["@"]},
		{"skillid":"69", "cmt":"","skillref":["@"]},
		{"skillid":"70", "cmt":"","skillref":["@"]},
		{"skillid":"71", "cmt":"","skillref":["@"]},*/
		{	"skillid":"72", "cmt":"BB ATK%","skillref":["bb atk% buff", "!% BB ATK%+ ", "buff turns (72)", "!Turns"]},
		//{"skillid":"73", "cmt":"","skillref":["@"]},
		{	"skillid":"74", "cmt":"Debuff ATK","skillref":["@"]},
		{	"skillid":"75", "cmt":"Debuff DEF","skillref":["@"]},
		/*{"skillid":"76", "cmt":"","skillref":["@"]},
		{"skillid":"77", "cmt":"","skillref":["@"]},
		{"skillid":"78", "cmt":"","skillref":["@"]},
		{"skillid":"79", "cmt":"","skillref":["@"]},
		{"skillid":"80", "cmt":"","skillref":["@"]},
		{"skillid":"81", "cmt":"","skillref":["@"]},
		{"skillid":"82", "cmt":"","skillref":["@"]},
		{"skillid":"83", "cmt":"","skillref":["@"]},
		{"skillid":"84", "cmt":"","skillref":["@"]},
		{"skillid":"85", "cmt":"","skillref":["@"]},
		{"skillid":"86", "cmt":"","skillref":["@"]},
		{"skillid":"87", "cmt":"","skillref":["@"]},
		{"skillid":"88", "cmt":"","skillref":["@"]},
		{"skillid":"89", "cmt":"","skillref":["@"]},
		{"skillid":"90", "cmt":"","skillref":["@"]},
		{"skillid":"91", "cmt":"","skillref":["@"]},
		{"skillid":"92", "cmt":"","skillref":["@"]},
		{"skillid":"93", "cmt":"","skillref":["@"]},
		{"skillid":"94", "cmt":"","skillref":["@"]},
		{"skillid":"95", "cmt":"","skillref":["@"]},
		{"skillid":"96", "cmt":"","skillref":["@"]},
		{"skillid":"97", "cmt":"","skillref":["@"]},
		{"skillid":"98", "cmt":"","skillref":["@"]},
		{"skillid":"99", "cmt":"","skillref":["@"]},
		{"skillid":"100", "cmt":"","skillref":["@"]},
		{"skillid":"101", "cmt":"","skillref":["@"]},
		{"skillid":"102", "cmt":"","skillref":["@"]},
		{"skillid":"103", "cmt":"","skillref":["@"]},
		{"skillid":"104", "cmt":"","skillref":["@"]},
		{"skillid":"105", "cmt":"","skillref":["@"]},
		{"skillid":"106", "cmt":"","skillref":["@"]},
		{"skillid":"107", "cmt":"","skillref":["@"]},
		{"skillid":"108", "cmt":"","skillref":["@"]},
		{"skillid":"109", "cmt":"","skillref":["@"]},
		{"skillid":"110", "cmt":"","skillref":["@"]},
		{"skillid":"111", "cmt":"","skillref":["@"]},
		{"skillid":"112", "cmt":"","skillref":["@"]},
		{"skillid":"113", "cmt":"","skillref":["@"]},
		{"skillid":"114", "cmt":"","skillref":["@"]},
		{"skillid":"115", "cmt":"","skillref":["@"]},
		{"skillid":"116", "cmt":"","skillref":["@"]},
		{"skillid":"117", "cmt":"","skillref":["@"]},
		{"skillid":"118", "cmt":"","skillref":["@"]},
		{"skillid":"119", "cmt":"","skillref":["@"]},
		{"skillid":"120", "cmt":"","skillref":["@"]},
		{"skillid":"121", "cmt":"","skillref":["@"]},
		{"skillid":"122", "cmt":"","skillref":["@"]},
		{"skillid":"123", "cmt":"","skillref":["@"]},
		{"skillid":"124", "cmt":"","skillref":["@"]},
		{"skillid":"125", "cmt":"","skillref":["@"]},
		{"skillid":"126", "cmt":"","skillref":["@"]},
		{"skillid":"127", "cmt":"","skillref":["@"]},
		{"skillid":"128", "cmt":"","skillref":["@"]},
		{"skillid":"129", "cmt":"","skillref":["@"]},
		{"skillid":"130", "cmt":"","skillref":["@"]},
		{"skillid":"131", "cmt":"","skillref":["@"]},*/
		{	"skillid":"132", "cmt":"OD Fill Rates","skillref":["@"]},
		/*{"skillid":"133", "cmt":"","skillref":["@"]},
		{"skillid":"134", "cmt":"","skillref":["@"]},
		{"skillid":"135", "cmt":"","skillref":["@"]},
		{"skillid":"136", "cmt":"","skillref":["@"]},
		{"skillid":"137", "cmt":"","skillref":["@"]},
		{"skillid":"138", "cmt":"","skillref":["@"]},
		{"skillid":"139", "cmt":"","skillref":["@"]},
		{"skillid":"140", "cmt":"","skillref":["@"]},
		{"skillid":"141", "cmt":"","skillref":["@"]},
		{"skillid":"142", "cmt":"","skillref":["@"]},
		{"skillid":"143", "cmt":"","skillref":["@"]},
		{"skillid":"144", "cmt":"","skillref":["@"]},
		{"skillid":"145", "cmt":"","skillref":["@"]},
		{"skillid":"146", "cmt":"","skillref":["@"]},
		{"skillid":"147", "cmt":"","skillref":["@"]},
		{"skillid":"148", "cmt":"","skillref":["@"]},
		{"skillid":"149", "cmt":"","skillref":["@"]},
		{"skillid":"150", "cmt":"","skillref":["@"]},
		{"skillid":"151", "cmt":"","skillref":["@"]},
		{"skillid":"152", "cmt":"","skillref":["@"]},
		{"skillid":"153", "cmt":"","skillref":["@"]},
		{"skillid":"154", "cmt":"","skillref":["@"]},
		{"skillid":"155", "cmt":"","skillref":["@"]},
		{"skillid":"156", "cmt":"","skillref":["@"]},
		{"skillid":"157", "cmt":"","skillref":["@"]},
		{"skillid":"158", "cmt":"","skillref":["@"]},
		{"skillid":"159", "cmt":"","skillref":["@"]},
		{"skillid":"160", "cmt":"","skillref":["@"]},
		{"skillid":"161", "cmt":"","skillref":["@"]},
		{"skillid":"162", "cmt":"","skillref":["@"]},
		{"skillid":"163", "cmt":"","skillref":["@"]},
		{"skillid":"164", "cmt":"","skillref":["@"]},
		{"skillid":"165", "cmt":"","skillref":["@"]},
		{"skillid":"166", "cmt":"","skillref":["@"]},
		{"skillid":"167", "cmt":"","skillref":["@"]},
		{"skillid":"168", "cmt":"","skillref":["@"]},
		{"skillid":"169", "cmt":"","skillref":["@"]},
		{"skillid":"170", "cmt":"","skillref":["@"]},
		{"skillid":"171", "cmt":"","skillref":["@"]},
		{"skillid":"172", "cmt":"","skillref":["@"]},
		{"skillid":"173", "cmt":"","skillref":["@"]},
		{"skillid":"174", "cmt":"","skillref":["@"]},
		{"skillid":"175", "cmt":"","skillref":["@"]},
		{"skillid":"176", "cmt":"","skillref":["@"]},
		{"skillid":"177", "cmt":"","skillref":["@"]},
		{"skillid":"178", "cmt":"","skillref":["@"]},
		{"skillid":"179", "cmt":"","skillref":["@"]},
		{"skillid":"180", "cmt":"","skillref":["@"]},
		{"skillid":"181", "cmt":"","skillref":["@"]},
		{"skillid":"182", "cmt":"","skillref":["@"]},
		{"skillid":"183", "cmt":"","skillref":["@"]},
		{"skillid":"184", "cmt":"","skillref":["@"]},
		{"skillid":"185", "cmt":"","skillref":["@"]},
		{"skillid":"186", "cmt":"","skillref":["@"]},
		{"skillid":"187", "cmt":"","skillref":["@"]},
		{"skillid":"188", "cmt":"","skillref":["@"]},
		{"skillid":"189", "cmt":"","skillref":["@"]},
		{"skillid":"190", "cmt":"","skillref":["@"]},
		{"skillid":"191", "cmt":"","skillref":["@"]},
		{"skillid":"192", "cmt":"","skillref":["@"]},
		{"skillid":"193", "cmt":"","skillref":["@"]},
		{"skillid":"194", "cmt":"","skillref":["@"]},
		{"skillid":"195", "cmt":"","skillref":["@"]},
		{"skillid":"196", "cmt":"","skillref":["@"]},
		{"skillid":"197", "cmt":"","skillref":["@"]},
		{"skillid":"198", "cmt":"","skillref":["@"]},
		{"skillid":"199", "cmt":"","skillref":["@"]},
		{"skillid":"200", "cmt":"","skillref":["@"]},*/
    ];