var lsParseObj=[
        {"skillid":"fire resist%", "skillref":["fire resist%", "!% Fire Resist"]},
        {"skillid":"water resist%", "skillref":["water resist%", "!% Water Resist"]},
        {"skillid":"earth resist%", "skillref":["earth resist%", "!% Earth Resist"]},
        {"skillid":"thunder resist%", "skillref":["thunder resist%", "!% Thunder Resist"]},
        {"skillid":"light resist%", "skillref":["light resist%", "!% Light Resist"]},
        {"skillid":"dark resist%", "skillref":["dark resist%", "!% Dark Resist"]},
        {"skillid":"hp drain chance%", "skillref":["hp drain chance%", "!% Chance Drain ", "hp drain% low", "!-", "hp drain% high", "!% HP"]},
        {"skillid":"bc fill per turn", "skillref":["bc fill per turn","!BC Fill Each Turn"]},
        {"skillid":"bc fill when attacking%", "skillref":["bc fill when attacking%","!% Chance ", "bc fill when attacking low", "!-", "bc fill when attacking low", "!BC Fill on ATK"]},
        {"skillid":"ignore def%", "skillref":["ignore def%","!% Chance Ignore DEF"]},
        {"skillid":"reduced bb bc cost%", "skillref":["!Reduce ","reduced bb bc cost%","!% BB Cost"]},
        {"skillid":"reduced bb bc use chance%", "skillref":["reduced bb bc use chance%","!% Chance Reduce ", "reduced bb bc use% low", "!-", "reduced bb bc use% high", "!% BB Gauge Used"]},
        {"skillid":"dmg reduction chance%", "skillref":["dmg reduction chance%", "!% Chance Reduce DMG (", "dmg reduction%", "!%)"]},
        {"skillid":"take 1 dmg%", "skillref":["take 1 dmg%", "!% Chance Reduce DMG to 1"]},
        {"skillid":"dmg% mitigation", "skillref":["!Reduce DMG (", "dmg% mitigation","!%)"]},
        {"skillid":"bb gauge fill rate%", "skillref":["bb gauge fill rate%", "!% BC Fill+"]},
        {"skillid":"hc effectiveness%", "skillref":["hc effectiveness%", "!% HC Fill+"]},
        {"skillid":"bc drop% for spark", "skillref":["bc drop% for spark", "!% Spark BC+"]},
        {"skillid":"hc drop% for spark", "skillref":["hc drop% for spark", "!% Spark HC+"]},
        {"skillid":"karma drop% for spark", "skillref":["karma drop% for spark", "!% Spark Karma+"]},
        {"skillid":"zel drop% for spark", "skillref":["zel drop% for spark", "!% Spark Zel+"]},
        {"skillid":"bc fill on spark%", "skillref":["bc fill on spark%", "!% Chance ", "bc fill on spark low", "!-", "bc fill on spark high", "!BC Fill on Spark"]},
	    {"skillid":"bc fill on crit%", "skillref":["bc fill on crit min", "!-", "bc fill on crit max", "!BC Fill on CRIT"]},
        {"skillid":"bc fill on enemy defeat%", "skillref":["bc fill on enemy defeat%", "!% Chance ", "bc fill on enemy defeat low", "!-", "bc fill on enemy defeat high", "!BC Fill on Enemy Kill"]},
        {"skillid":"bc fill when attacked%", "skillref":["bc fill when attacked%", "!% Chance ", "bc fill when attacked low", "!-", "bc fill when attacked high", "!BC Fill when ATKed"]},
        {"skillid":"bc filled when attacked while guarded", "skillref":["bc filled when attacked while guarded", "!BC Fill when ATKed on Guard"]},
        {"skillid":"guard increase mitigation%", "skillref":["!Reduce DMG (", "guard increase mitigation%", "!%) on Guard"]},
        {"skillid":"dmg% to hp% when attacked chance%", "skillref":["dmg% to hp% when attacked chance%", "!% Chance Heal ", "dmg% to hp% when attacked low", "!-", "dmg% to hp% when attacked high", "!% DMG when ATKed"]},
        {"skillid":"turn heal high", "skillref":["!Heal Each Turn (","turn heal low","!-","turn heal high","!)"]},
        {"skillid":"defense% ignore", "skillref":["!Ignore DEF ", "target type", "! ","defense% ignore turns (39)", "!Turns"]},
        {"skillid":"damage% for spark", "skillref":["damage% for spark", "!% Spark DMG+"]},
        {"skillid":"crit multiplier%", "skillref":["crit multiplier%", "!% CRIT DMG+"]},
        {"skillid":"bb atk% buff", "skillref":["bb atk% buff", "!% BB ATK%+"]},
        {"skillid":"hit increase/hit", "skillref":["!Normal HitCount +", "hit increase/hit", "!00% (", "extra hits dmg%", "!% DMG)"]},
        {"skillid":"atk% extra buff based on hp", "skillref":["atk% base buff", "!-", "atk% extra buff based on hp", "!% ATK+ Based on HP ", "buff proportional to hp"]},
        {"skillid":"def% extra buff based on hp", "skillref":["def% base buff", "!-", "def% extra buff based on hp", "!% DEF+ Based on HP ", "buff proportional to hp"]},
        {"skillid":"dmg% reflect chance%", "skillref":["dmg% reflect chance%", "!% Chance Reflect ", "dmg% reflect low", "!-", "dmg% reflect high", "!% DMG"]},
        {"skillid":"base crit% resist", "skillref":["!Nulls CRIT"]},
        {"skillid":"crit chance base resist%", "skillref":["!Nulls CRIT"]},
		{"skillid":"base spark dmg% resist", "skillref":["!Nulls SPARK DMG"]},
        {"skillid":"strong base element damage resist%", "skillref":["!Nulls Elemental Weakness"]},
        {"skillid":"element weakness", "skillref":["elemental weakness multiplier%", "!% Element Weakness DMG+ ","@"]},
		{"skillid":"atk% buff when enemy has ailment", "skillref":["atk% buff when enemy has ailment", "!% ATK%+ to Ails-Infected Enemies ","@"]},
		{"skillid":"element mitigate", "skillref":["dmg% mitigation for elemental attacks", "!% Element Atk Mitigated","@"]},
        {"skillid":"crystals buff", "skillref":["@"]},
        {"skillid":"stats buff", "skillref":["@"]},
        {"skillid":"xturns buff", "skillref":["@", "first x turns", "!Turns"]},
        {"skillid":"ails", "skillref":["@"]},
		{"skillid":"triggered effect", "skillref":["!Add  [","#","!] ","@"]},
        {"skillid":"ails resist", "skillref":["!Null Ailments (","@","!)"]},
        {"skillid":"db resist", "skillref":["!Null Debuff (","@","!)"]},
        {"skillid":"ignore def resist chance%", "skillref":["!Null Def Ignore"]},
		{"skillid":"bc filled on guard", "skillref":["bc filled on guard", "!BC fill on Guard"]},
		{"skillid":"od fill rate%", "skillref":["od fill rate%", "!% OD Fill+"]},
		{"skillid":"spark count buff activation", "skillref":["!Buff [", "#","!] ", "!after spark ", "spark count buff activation", "! times"]},
		{"skillid":"hp below % buff activation", "skillref":["!Buff [", "#","!] ", "!when hp below ", "hp below % buff activation", "!%"]},
     	{"skillid":"damage threshold buff activation", "skillref":["!Buff [", "#","!] ", "!when TAKEN more than ", "damage threshold buff activation", "! damage"]},
     	{"skillid":"damage dealt threshold buff activation", "skillref":["!Buff [", "#","!] ", "!when DEALT more than ", "damage dealt threshold buff activation", "! damage"]},
    	{"skillid":"bc receive count buff activation", "skillref":["!Buff [", "#","!] ", "!when RECEIVED more than ", "bc receive count buff activation", "! BCs"]},
    	{"skillid":"hc receive count buff activation", "skillref":["!Buff [", "#","!] ", "!when RECEIVED more than ", "hc receive count buff activation", "! HCs"]},
		{"skillid":"on crit activation chance%", "skillref":["!Buff [", "#","!] ", "!when CRIT (", "on crit activation chance%", "!% Chance)"]},
		{"skillid":"heal on spark%", "skillref":["heal on spark%", "!% Chance Heal ", "heal on spark low", "!-", "heal on spark high", "! on SPARK"]},
		{"skillid":"angel idol recover counts", "skillref":["angel idol recover counts", "! Time(s) (", "angel idol recover chance% low", "!%-", "angel idol recover chance% high", "!%) Chance Withstand a KNOCKOUT ATK"]},
		{"skillid":"spark debuff chance%", "skillref":["spark debuff chance%", "!% Chance Debuff Enemies to TAKE ", "spark debuff%", "!% DMG+ on SPARK for ", "spark debuff turns", "!Turn(s)"]},
        {"skillid":"xp gained increase%", "skillref":["xp gained increase%", "!% QUEST EXP+"]},
		{"skillid":"damage dealt threshold activation", "skillref":["increase bb gauge", "!BC fill when DEALT ", "damage threshold activation", "! DMG"]},
		{"skillid":"damage threshold activation", "skillref":["increase bb gauge", "!BC fill when TAKEN ", "damage threshold activation", "! DMG"]},
		{"skillid":"hc receive count activation", "skillref":["increase bb gauge", "!BC fill when RECEIVE ", "hc receive count activation", "! HC"]},
		{"skillid":"hp% recover on enemy defeat low", "skillref":["!Heal ", "hp% recover on enemy defeat low", "!-", "hp% recover on enemy defeat high", "!% HP when Enemy DEFEATED"]},
		{"skillid":"hp% recover on battle win low", "skillref":["!Heal ", "hp% recover on battle win low", "!-", "hp% recover on battle win high", "!% HP when Battle WON"]},
		{"skillid":"battle end bc fill low", "skillref":["battle end bc fill low", "!-", "battle end bc fill high", "!% BC Fill when Battle WON"]},
		{"skillid":"target% chance", "skillref":["target% chance", "!% Chance to be Targeted", "@"]},
		{"skillid":"additional actions", "skillref":["additional actions", "! Action+"]},
      ];