var lsParseObj=[
		{	"skillid":"1", "cmt":"Stats Buff c:None","skillref":["@"]},
		{	"skillid":"2", "cmt":"Stats Buff c:Element","skillref":["@"]},
		{	"skillid":"3", "cmt":"Stats Buff c:Type","skillref":["@"]},
		{	"skillid":"4", "cmt":"Ailments Resist", "skillref":["@"]},
		{	"skillid":"5", "cmt":"Elemental Resist", "skillref":["!Resist Elemental DMG (","@","!)"]},
		//{"skillid":"6", "cmt":"","skillref":["@"]},
		//{"skillid":"7", "cmt":"","skillref":["@"]},
		{	"skillid":"8", "cmt":"Mitigate DMG","skillref":["!Reduce DMG (", "dmg% mitigation","!%)"]},
		{	"skillid":"9", "cmt":"BC Fill Per Turn","skillref":["bc fill per turn","!BC Fill Per Turn"]},
		{	"skillid":"10", "cmt":"HC Fill Rate+","skillref":["hc effectiveness%", "!% HC Fill Rate+"]},
		{	"skillid":"11", "cmt":"Stats Buff c:HP","skillref":["@"]},
		{	"skillid":"12", "cmt":"Drop Rate% c:HP","skillref":["@","! (HP<","hp below % buff requirement","!%)"]},
		{	"skillid":"13", "cmt":"BC Fill on Enemy Kill", "skillref":["bc fill on enemy defeat%", "!% Chance ", "bc fill on enemy defeat low", "!-", "bc fill on enemy defeat high", "!BC Fill on Enemy Kill"]},
		{	"skillid":"14", "cmt":"Chance Reduce DMG","skillref":["dmg reduction chance%", "!% Chance Reduce DMG (", "dmg reduction%", "!%)"]},
		{	"skillid":"15", "cmt":"Heal c:Defeat","skillref":["!Heal ", "hp% recover on enemy defeat low", "!-", "hp% recover on enemy defeat high", "!% HP when Enemy DEFEATED"]},
		{	"skillid":"16", "cmt":"Heal c:Win","skillref":["!Heal ", "hp% recover on battle win low", "!-", "hp% recover on battle win high", "!% HP when Battle WON"]},
		{	"skillid":"17", "cmt":"Chance HP Drain","skillref":["hp drain chance%", "!% Chance Drain ", "hp drain% low", "!-", "hp drain% high", "!% HP"]},
		//{"skillid":"18", "cmt":"","skillref":["@"]},
		{	"skillid":"19", "cmt":"Drop Rate%","skillref":["@"]},
		{	"skillid":"20", "cmt":"Ailment%","skillref":["@"]},
		{	"skillid":"21", "cmt":"XTurn Stats Buff","skillref":["@", "first x turns", "!Turns"]},
		//{"skillid":"22", "cmt":"","skillref":["@"]},
		{	"skillid":"23", "cmt":"BC Fill c:Won","skillref":["battle end bc fill low", "!-", "battle end bc fill high", "!% BC Fill when Battle WON"]},
		{	"skillid":"24", "cmt":"Heal when ATKed","skillref":["dmg% to hp% when attacked chance%", "!% Chance Heal ", "dmg% to hp% when attacked low", "!-", "dmg% to hp% when attacked high", "!% DMG when ATKed"]},
		{	"skillid":"25", "cmt":"BC Fill when ATKed","skillref":["bc fill when attacked%", "!% Chance ", "bc fill when attacked low", "!-", "bc fill when attacked high", "!BC Fill when ATKed"]},
		{	"skillid":"26", "cmt":"DMG Reflect","skillref":["dmg% reflect chance%", "!% Chance Reflect ", "dmg% reflect low", "!-", "dmg% reflect high", "!% DMG"]},
		{	"skillid":"27", "cmt":"Target Chance","skillref":["target% chance", "!% Chance to be Targeted", "@"]},
		{	"skillid":"28", "cmt":"Target Chance c:HP","skillref":["target% chance", "!% Chance to be Targeted", "! (HP<","hp below % passive requirement","!%)"]},
		{	"skillid":"29", "cmt":"Ignore Def","skillref":["ignore def%","!% Chance Ignore DEF"]},
		{	"skillid":"30", "cmt":"Stats Buff c:BB","skillref":["@"]},
		{	"skillid":"31", "cmt":"Spark DMG+/BC+","skillref":["@","! on Spark"]},
		{	"skillid":"32", "cmt":"BC Fill Rate+","skillref":["bb gauge fill rate%", "!% BC Fill Rate+"]},
		{	"skillid":"33", "cmt":"Heal Over Turn","skillref":["!Heal Over Turn (","turn heal low","!-","turn heal high","!)"]},
		{	"skillid":"34", "cmt":"Crit DMG+","skillref":["crit multiplier%", "!% CRIT DMG+"]},
		{	"skillid":"35", "cmt":"BC Fill on ATKing","skillref":["bc fill when attacking%","!% Chance ", "bc fill when attacking low", "!-", "bc fill when attacking low", "!BC Fill on ATKing"]},
		{	"skillid":"36", "cmt":"Additional Action","skillref":["additional actions", "!Additional Action(s)"]},
		{	"skillid":"37", "cmt":"Normal HitCount+","skillref":["!Normal HitCount +", "hit increase/hit", "!00% (", "@", "!% DMG+)"]},
		//{"skillid":"38", "cmt":"","skillref":["@"]},
		//{"skillid":"39", "cmt":"","skillref":["@"]},
		{	"skillid":"40", "cmt":"Stats Convert","skillref":["!Convert ","converted attribute","! to (","@","!)"]},
		{	"skillid":"41", "cmt":"Stats Buff c:ElementCount","skillref":["@"]},
		{	"skillid":"42", "cmt":"Stats Buff c:Gender","skillref":["@"]},
		{	"skillid":"43", "cmt":"DMG to 1","skillref":["take 1 dmg%", "!% Chance Reduce DMG to 1"]},
		{	"skillid":"44", "cmt":"Stats Buff in Number","skillref":["@"]},
		{	"skillid":"45", "cmt":"Negate Crit DMG","skillref":["!Negate Crit DMG (", "base crit% resist","!+","buff crit% resist", "!%)"]},
		{	"skillid":"46", "cmt":"Stats Base Buff c:HP","skillref":["@","!Based on HP ", "buff proportional to hp"]},
		{	"skillid":"47", "cmt":"BC Fill on Spark","skillref":["bc fill on spark%", "!% Chance ", "bc fill on spark low", "!-", "bc fill on spark high", "!BC Fill on Spark"]},
		{	"skillid":"48", "cmt":"Reduce BB Cost REQUIRED","skillref":["!Reduce ","reduced bb bc cost%","!% BB Cost REQUIRED"]},
		{	"skillid":"49", "cmt":"Reduce BB Gauge USED","skillref":["reduced bb bc use chance%","!% Chance Reduce ", "reduced bb bc use% low", "!-", "reduced bb bc use% high", "!% BB Gauge USED"]},
		{	"skillid":"50", "cmt":"Elemental Weakness DMG+","skillref":["elemental weakness multiplier%", "!% Element Weakness DMG+ ","@"]},
		//{"skillid":"51", "cmt":"","skillref":["@"]},
		//{"skillid":"52", "cmt":"","skillref":["@"]},
		{	"skillid":"53", "cmt":"Negate Crit Chance/DMG","skillref":["!Negate DMG Factors (","@","!)"]},
		//{"skillid":"54", "cmt":"","skillref":["@"]},
		{	"skillid":"55", "cmt":"Trigger Buff","skillref":["!Buff  [","#","!] ","!(HP <", "hp below % buff activation", "!)"]},
		//{"skillid":"56", "cmt":"","skillref":["@"]},
		//{"skillid":"57", "cmt":"","skillref":["@"]},
		{	"skillid":"58", "cmt":"Reduce DMG on Guard","skillref":["!Reduce DMG (", "guard increase mitigation%", "!%) on Guard"]},
		{	"skillid":"59", "cmt":"BC Fill when ATKed on Guard","skillref":["bc filled when attacked while guarded", "!BC Fill when ATKed on Guard"]},
		//{"skillid":"60", "cmt":"","skillref":["@"]},
		{	"skillid":"61", "cmt":"BC Fill on Guard","skillref":["bc filled on guard", "!BC Fill on Guard"]},
		{	"skillid":"62", "cmt":"Mitigate Elemental ATK","skillref":["dmg% mitigation for elemental attacks", "!% Element Atk Mitigated","@"]},
		{	"skillid":"63", "cmt":"Mitigate Elemental ATK XTurn","skillref":["dmg% mitigation for elemental attacks", "!% Element Atk Mitigated ","@", "! For the First ", "dmg% mitigation for elemental attacks buff for first x turns", "!Turns"]},
		{	"skillid":"64", "cmt":"BB ATK%+","skillref":["bb atk% buff", "!% BB ATK%+"]},
		{	"skillid":"65", "cmt":"BC Fill on Crit","skillref":["bc fill on crit min", "!-", "bc fill on crit max", "!BC Fill on Crit"]},
		{	"skillid":"66", "cmt":"Trigger Effect","skillref":["!Add  [","#","!] ","@"]},
		//{"skillid":"67", "cmt":"","skillref":["@"]},
		//{"skillid":"68", "cmt":"","skillref":["@"]},
		{	"skillid":"69", "cmt":"Angel Idol Chance","skillref":["angel idol recover counts", "! Time(s) (", "angel idol recover chance% low", "!%-", "angel idol recover chance% high", "!%) Chance Withstand a KNOCKOUT ATK"]},
		{	"skillid":"70", "cmt":"OD Fill Rate+","skillref":["od fill rate%", "!% OD Fill Rate+"]},
		{	"skillid":"71", "cmt":"Ails Counter","skillref":["!Chance to Counter Inflect ","@"]},
		{	"skillid":"72", "cmt":"BC/Heal at Begin","skillref":["@"]},
		{	"skillid":"73", "cmt":"Ails/Debuff Resists","skillref":["@"]},
		{"skillid":"74", "cmt":"ATK%+ to Ailed","skillref":["atk% buff when enemy has ailment", "!% ATK%+ to Ails-Infected Enemies ","@"]},
		{	"skillid":"75", "cmt":"Spark Debuff","skillref":["spark debuff chance%", "!% Chance Debuff Enemies to TAKE ", "spark debuff%", "!% DMG+ on SPARK for ", "spark debuff turns", "!Turn(s)"]},
		//{"skillid":"76", "cmt":"","skillref":["@"]},
		{	"skillid":"77", "cmt":"Negate Spark DMG","skillref":["!Negate Spark DMG (", "base spark dmg% resist","!+","buff spark dmg% resist", "!%)"]},
		{	"skillid":"78", "cmt":"Trigger Buff","skillref":["!Buff  [","#","!] ","!(Taken ", "damage threshold buff activation" ,"!DMG)"]},
		{	"skillid":"79", "cmt":"BB DMG Taken","skillref":["increase bb gauge", "!BC fill when TAKEN ", "damage threshold activation", "! DMG"]},
		{	"skillid":"80", "cmt":"Trigger Buff","skillref":["!Buff  [","#","!] ","!(Deal ", "damage dealt threshold buff activation" ,"!DMG)"]},
		{	"skillid":"81", "cmt":"BB DMG Dealt","skillref":["increase bb gauge", "!BC fill when DEALT ", "damage dealt threshold activation", "! DMG"]},
		{	"skillid":"82", "cmt":"Trigger Buff","skillref":["!Buff  [","#","!] ","!(Receive ", "bc receive count buff activation" ,"!BC)"]},
		//{"skillid":"83", "cmt":"","skillref":["@"]},
		{	"skillid":"84", "cmt":"Trigger Buff","skillref":["!Buff  [","#","!] ","!(Receive ", "hc receive count buff activation" ,"!HC)"]},
		//{"skillid":"85", "cmt":"","skillref":["@"]},
		{	"skillid":"86", "cmt":"Trigger Buff","skillref":["!Buff  [","#","!] ","!(Deal ", "spark count buff activation" ,"!Spark)"]},
		//{"skillid":"87", "cmt":"","skillref":["@"]},
		//{"skillid":"88", "cmt":"","skillref":["@"]},
		{	"skillid":"89", "cmt":"Trigger Buff","skillref":["!Buff  [","#","!] ","!(On Crit)"]},
		//{"skillid":"90", "cmt":"","skillref":["@"]},
		{	"skillid":"91", "cmt":"","skillref":["@"]},
		{	"skillid":"92", "cmt":"Negate Def Ignore DMG","skillref":["!Negate Def Ignore DMG (", "ignore def resist chance%", "!%)"]},
		{"skillid":"93", "cmt":"!Passive Elemental ATK","skillref":["!All Elements Added to ATK"]},
		//{"skillid":"94", "cmt":"","skillref":["@"]},
		//{"skillid":"95", "cmt":"","skillref":["@"]},
		{	"skillid":"96", "cmt":"Normal AOE ATK Chance","skillref":["chance to aoe","!% Chance for Normal AOE ATK (","aoe atk inc%", "!% DMG+)" ]},
		{	"skillid":"97", "cmt":"Quest EXP+","skillref":["xp gained increase%", "!% QUEST EXP+"]},
		{"skillid":"98", "cmt":"","skillref":["@"]},
		{	"skillid":"99", "cmt":"Sphere can be equipped regardless of category","skillref":["!Sphere can be equipped regardless of category"]},
		{	"skillid":"100", "cmt":"Crit Spark Chance","skillref":["@"]},
		{	"skillid":"101", "cmt":"Heal on Spark","skillref":["heal on spark%", "!% Chance Heal ", "heal on spark low", "!-", "heal on spark high", "! on SPARK"]},
		{	"skillid":"102", "cmt":"Passive Element Added","skillref":["!Add Element(s) to ATK ", "@"]},
		{	"skillid":"103", "cmt":"BB ATK% c:HP","skillref":["@"]},
		{"skillid":"104", "cmt":"Spark DMG+ c:HP","skillref":["@"]},
		{	"skillid":"105", "cmt":"Incredimentally Stats Buff","skillref":["!Incredimentally increase up to ", "@", "! within ", "turn count", "!Turns"]},
		{	"skillid":"106", "cmt":"Angel Idol c:Overdrive","skillref":["@"]},
		//{"skillid":"107", "cmt":"","skillref":["@"]},
		//{"skillid":"108", "cmt":"","skillref":["@"]},
		{	"skillid":"109", "cmt":"BC Fill Rate- Chance","skillref":["@"]},
		{	"skillid":"110", "cmt":"BB Gauge Drain Chance","skillref":["@"]},
		{	"skillid":"111", "cmt":"Skill AI Rate+","skillref":["@"]},
		{	"skillid":"112", "cmt":"ABP/CBP Pts+","skillref":["@"]},
		{	"skillid":"113", "cmt":"BB ATK% c:HP","skillref":["@"]},
		{	"skillid":"143", "cmt":"ATK Cap","skillref":["@"]},
      ];